### PR TITLE
Add scripts to run in docker and compile locally

### LINKED ISSUE #1: Add scripts to simplify deployment and usage
Feedback from Dave W.:

> Whatever you can do to make it SUPER EASY to use, is always good. If you look at the root directory of my OWASP project: https://github.com/OWASP/Benchmark you'll see things like:
>
> - URL file that points to the web app home page
> - various prebuilt scripts to do common tasks

### PR DESCRIPTION
**Pull request by pkruk2**
Closes #1

### CODE REVIEW

**Comment by tobyash86** [comment]
Do these scripts work the same on Linux and Windows containers?

**Comment by tobyash86** [comment]
Also I have some second thoughts... Those scripts will work on Windows but not on Linux...

**Comment by pkruk2** [comment]
I have not tested the Linux scripts, as I didn't have Linux machine available. I just copied commands from the readme.md. There was no information that they are Windows-specific, so I assumed they work on Linux.
Why they won't work on Linux?

**Comment by tobyash86** [comment]
We need to verify it. Accepting for now.

**Pull request merged**
