### PR TITLE
#46: Unifuing orders view format with receipt and cart

### PR DESCRIPTION
**Pull request by tobyash86**

### CODE REVIEW

**Comment by tobyash86** [comment]
@pkruk2 please share/propose other approaches. I will try to improve it.

**Comment by pkruk2** [comment]
I'd keep separate classes for both of them and then in css do sth like
```
.receipt th { text-align: left; }
.receipts th { text-align: center; }
```

(if that's the intention)

**Comment by tobyash86** [comment]
In the .css there was no .receipts style defined. This is why I used shorthand of receipt with a modification.
As I think of it now, alternative is to create .receipts from scratch.
What's your opinion?

**Comment by pkruk2** [comment]
I see. You mean you'd have to duplicate every css definition for receipt class.

From what I see, the only difference is the text-align of header - one is left aligned, the other is center aligned. Maybe we could have both aligned the same?

**Comment by tobyash86** [comment]
I will see how will it look like. Thanks.

**Comment by tobyash86** [comment]
Done, please CR.

**Review by pkruk2 — APPROVED** [review]
Looks good now. Much simpler :)

**Pull request merged**
